/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Used by the compose healthcheck. Answers as soon as Django is serving; it does not touch the database, Redis or the AI service.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List jobs
         * @description Newest first, paginated 20 per page via the `page` query parameter.
         */
        get: operations["jobs_list"];
        put?: never;
        /**
         * Upload media and queue a job
         * @description `multipart/form-data` with a single `file` part — an image (.jpg/.jpeg/.png/.webp/.bmp) or a video (.mp4/.mov/.avi/.mkv/.webm). Returns the job in `queued` state; poll `GET /api/jobs/{id}` for the result.
         */
        post: operations["jobs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a job
         * @description The polling target. Re-request until `status` is `done` or `failed`; `detections` and `annotated_frame_urls` are only populated once `done`.
         */
        get: operations["jobs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Detection: {
            readonly id: number;
            readonly plate_text: string;
            /** Format: double */
            readonly confidence: number;
            /** @description [x1, y1, x2, y2] pixel coords, top-left origin */
            readonly bbox: number[];
            readonly frame_index: number;
            readonly timestamp_ms: number | null;
            readonly crop_url: string | null;
        };
        Health: {
            status: string;
        };
        /** @description Read shape returned by create, retrieve and list. The polling target. */
        Job: {
            /** Format: uuid */
            readonly id: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly media_type: components["schemas"]["MediaTypeEnum"];
            readonly source_filename: string;
            readonly media_url: string | null;
            readonly error: string;
            readonly frame_count: number | null;
            readonly video_analysis: components["schemas"]["VideoAnalysis"] | null;
            readonly annotated_frame_urls: string[];
            readonly detections: components["schemas"]["Detection"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly started_at: string | null;
            /** Format: date-time */
            readonly finished_at: string | null;
        };
        /** @description Accepts the multipart upload and persists it to the shared media volume. */
        JobCreateRequest: {
            /** Format: binary */
            file: string;
        };
        /**
         * @description * `image` - Image
         *     * `video` - Video
         * @enum {string}
         */
        MediaTypeEnum: "image" | "video";
        PaginatedJobList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Job"][];
        };
        /**
         * @description * `queued` - Queued
         *     * `processing` - Processing
         *     * `done` - Done
         *     * `failed` - Failed
         * @enum {string}
         */
        StatusEnum: "queued" | "processing" | "done" | "failed";
        /**
         * @description Shape of DRF's 400 body, so the schema documents the failure case too.
         *
         *     DRF keys validation errors by field name; the only writable field here is
         *     `file`, so that is the only key an upload can fail on.
         */
        ValidationError: {
            /** @description Reasons the upload was rejected: too large, or an unsupported type. */
            file?: string[];
        };
        VideoAnalysis: {
            /** Format: double */
            readonly sample_fps: number;
            readonly sampled_frame_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    jobs_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJobList"];
                };
            };
        };
    };
    jobs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["JobCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationError"];
                };
            };
        };
    };
    jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Job UUID returned by the upload. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
        };
    };
}
