# Generated by Django 5.2.17 on 2026-09-20 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=8)),
                ('source_filename', models.CharField(max_length=255)),
                ('media_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('result_raw', models.JSONField(blank=True, null=True)),
                ('annotated_frames', models.JSONField(blank=True, default=list)),
                ('frame_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(blank=True, max_length=32)),
                ('confidence', models.FloatField()),
                ('bbox', models.JSONField(help_text='[x1, y1, x2, y2] pixel coords, top-left origin')),
                ('frame_index', models.PositiveIntegerField(default=0)),
                ('timestamp_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('crop_path', models.CharField(max_length=512)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='jobs.job')),
            ],
            options={
                'ordering': ['frame_index', 'id'],
            },
        ),
    ]
